// earn-online-app/frontend-react/src/pages/Home.tsx
import React from 'react';
import AppList from '../components/AppList';
import Wishlist from '../components/Wishlist';

const Home: React.FC = () => {
    return (
        <div>
            <h1>Discover New Ways to Earn Money Online!</h1>
            <p>
                Hey there! Are you looking for ways to earn some extra money online? 
                I've discovered a fantastic resource that I'd love to share with you!
            </p>
            <p>
                What sets this site apart is that it's compiled based on my own research and testing. 
                I've tried out various opportunities and outlined which ones are worth your time and which ones aren't.
            </p>
            <h2>Opportunities to Earn Money Online:</h2>
            <AppList />
            <h2>Your Wishlist:</h2>
            <Wishlist />
        </div>
    );
};

export default Home;

// earn-online-app/frontend-vue/src/views/Home.vue
<template>
  <div class="home">
    <h1>Discover New Ways to Earn Money Online!</h1>
    <p>
      Hey there! Are you looking for ways to earn some extra money online?
      I've discovered a fantastic resource that I'd love to share with you!
    </p>
    <p>
      What sets this site apart is that it's compiled based on my own research
      and testing. I've tried out various opportunities and outlined which ones
      are worth your time and which ones aren't.
    </p>
    <h2>Opportunities to Earn Money Online:</h2>
    <ul>
      <li>Signups and rewards</li>
      <li>Online surveys</li>
      <li>Learn and earn quizzes</li>
      <li>Crypto and NFT gaming</li>
      <li>Earning evidence</li>
      <li>Discounts and coupons</li>
      <li>Referral links</li>
      <li>Tips and tricks</li>
    </ul>
    <p>
      You'll get an honest and realistic view of what works and what doesn't,
      along with my personal insights and recommendations to help you make
      informed decisions and avoid wasting time on opportunities that aren't
      worth it.
    </p>
    <p>
      Take a look and see what opportunities resonate with you. I hope you find
      something that helps you achieve your financial goals!
    </p>
  </div>
</template>

<script lang="ts">
export default {
  name: 'Home',
};
</script>

<style scoped>
.home {
  padding: 20px;
  text-align: center;
}
</style>
